namespace FoodDeliveryPolaris.Models;

/// <summary>
/// Represents a menu item available at a restaurant.
/// Contains item details, pricing, availability status, cuisine type, and preparation time.
/// </summary>
public class MenuItem
{
    /// <summary>
    /// Gets or sets the unique identifier for the menu item.
    /// Auto-generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the name of the menu item.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the price of the menu item.
    /// </summary>
    public double Price { get; set; }

    /// <summary>
    /// Gets or sets whether the menu item is currently available for ordering.
    /// Defaults to true.
    /// </summary>
    public bool Available { get; set; } = true;

    /// <summary>
    /// Gets or sets the cuisine type of this menu item.
    /// Every dish has its own cuisine (e.g., "Margherita Pizza" ? Italian, "Paneer Butter Masala" ? Indian).
    /// </summary>
    public CuisineType CuisineType { get; set; }

    /// <summary>
    /// Gets or sets the preparation time in minutes for this menu item.
    /// Used for delivery time estimation.
    /// </summary>
    public int PreparationTimeMinutes { get; set; } = 20;
}
