namespace FoodDeliveryPolaris.Models;

/// <summary>
/// Represents a food delivery order in the system.
/// Contains order details, items, status tracking, and payment information.
/// Tracks the complete lifecycle of an order from placement to delivery.
/// </summary>
public class Order
{
    /// <summary>
    /// Gets or sets the unique identifier for the order.
    /// Auto-generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the ID of the user who placed the order.
    /// References the User entity.
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Gets or sets the ID of the restaurant fulfilling the order.
    /// References the Restaurant entity.
    /// </summary>
    public int RestaurantId { get; set; }

    /// <summary>
    /// Gets or sets the ID of the rider assigned to deliver the order.
    /// References the Rider entity. Null until rider is assigned.
    /// </summary>
    public int? RiderId { get; set; }

    /// <summary>
    /// Gets or sets the list of items included in this order.
    /// Initialized as an empty list.
    /// </summary>
    public List<OrderItem> Items { get; set; } = new();

    /// <summary>
    /// Gets or sets the total amount for the order.
    /// Simplified: Total = sum of all item prices (no tax or delivery fee).
    /// </summary>
    public double Total { get; set; }

    /// <summary>
    /// Gets or sets the current status of the order in its lifecycle.
    /// Tracks order progression from Placed through Delivered or Cancelled.
    /// Defaults to OrderStatus.Placed.
    /// </summary>
    public OrderStatus Status { get; set; } = OrderStatus.Placed;

    /// <summary>
    /// Gets or sets the payment status of the order.
    /// Tracks whether payment has been received, is pending, or has failed.
    /// Defaults to PaymentStatus.NotPaid.
    /// </summary>
    public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.NotPaid;

    /// <summary>
    /// Gets or sets the date and time when the order was placed.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the date and time when the order was last updated.
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the date and time when the order was completed (delivered or cancelled).
    /// Null if order is still in progress.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Gets or sets the delivery address for this order.
    /// </summary>
    public Location DeliveryAddress { get; set; } = new Location();

    /// <summary>
    /// Gets or sets special instructions or notes for the order.
    /// </summary>
    public string Notes { get; set; } = string.Empty;
}
