namespace FoodDeliveryPolaris.Models;

/// <summary>
/// Represents a restaurant in the food delivery platform.
/// Contains restaurant information, location, operational status, menu, and delivery constraints.
/// </summary>
public class Restaurant
{
    /// <summary>
    /// Gets or sets the unique identifier for the restaurant.
    /// Auto-generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the name of the restaurant.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the phone number of the restaurant.
    /// </summary>
    public string Phone { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the physical address of the restaurant.
    /// Includes street, city, ZIP code, and geographical coordinates.
    /// </summary>
    public Address Address { get; set; } = new Address();

    /// <summary>
    /// Gets or sets whether the restaurant is currently open for business.
    /// Defaults to true.
    /// </summary>
    public bool IsOpen { get; set; } = true;

    /// <summary>
    /// Gets or sets the delivery radius in kilometers.
    /// Restaurants often limit delivery zones (e.g., "3 km radius only").
    /// Helps quickly eliminate far restaurants before doing costlier distance/time checks.
    /// Defaults to 5 km.
    /// </summary>
    public double DeliveryRadiusKm { get; set; } = 5.0;

    /// <summary>
    /// Gets or sets the average preparation time in minutes for orders from this restaurant.
    /// Defaults to 20 minutes.
    /// </summary>
    public int AveragePreparationTimeMinutes { get; set; } = 20;

    /// <summary>
    /// Gets or sets the restaurant's rating (0-5 stars).
    /// Used for ranking recommendations.
    /// Defaults to 4.0.
    /// </summary>
    public double Rating { get; set; } = 4.0;

    /// <summary>
    /// Gets or sets the list of menu items offered by the restaurant.
    /// Initialized as an empty list.
    /// </summary>
    public List<MenuItem> Menu { get; set; } = new();
}
