namespace FoodDeliveryPolaris.Models;

/// <summary>
/// Represents a rider (delivery driver) in the food delivery system.
/// Contains rider identification, current location, contact information, vehicle details, and availability status.
/// </summary>
public class Rider
{
    /// <summary>
    /// Gets or sets the unique identifier for the rider.
    /// Auto-generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the name of the rider.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the current real-time location of the rider.
    /// Updated during active deliveries for tracking purposes.
    /// </summary>
    public Location CurrentLocation { get; set; } = new Location();

    /// <summary>
    /// Gets or sets the email address of the rider.
    /// </summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the phone number of the rider.
    /// </summary>
    public string Phone { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the vehicle registration number of the rider.
    /// </summary>
    public string VehicleNumber { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the current status of the rider.
    /// Indicates if the rider is Available, Busy, or Offline.
    /// Defaults to Available.
    /// </summary>
    public RiderStatus RiderStatus { get; set; } = RiderStatus.Available;
}
