namespace FoodDeliveryPolaris.Models;

/// <summary>
/// Represents a user (customer) in the food delivery system.
/// Contains user identification, contact information, and delivery address.
/// </summary>
public class User
{
    /// <summary>
    /// Gets or sets the unique identifier for the user.
    /// Auto-generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the name of the user.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the email address of the user.
    /// </summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the phone number of the user.
    /// </summary>
    public string Phone { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the delivery address of the user.
    /// Includes street, city, ZIP code, and geographical coordinates.
    /// </summary>
    public Address Address { get; set; } = new Address();
}
